# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\"\x15\n\x07MovieID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\nMovieTitle\x12\r\n\x05title\x18\x01 \x01(\t\"/\n\x11MovieUpdateRating\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\"H\n\tMovieData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x07\n\x05\x45mpty2\x88\x02\n\x05Movie\x12&\n\x0cGetMovieByID\x12\x08.MovieID\x1a\n.MovieData\"\x00\x12\'\n\rGetListMovies\x12\x06.Empty\x1a\n.MovieData\"\x00\x30\x01\x12\'\n\x0b\x43reateMovie\x12\n.MovieData\x1a\n.MovieData\"\x00\x12,\n\x0fGetMovieByTitle\x12\x0b.MovieTitle\x1a\n.MovieData\"\x00\x12 \n\x08\x44\x65lMovie\x12\x08.MovieID\x1a\x08.MovieID\"\x00\x12\x35\n\x11UpdateMovieRating\x12\x12.MovieUpdateRating\x1a\n.MovieData\"\x00\x62\x06proto3')



_MOVIEID = DESCRIPTOR.message_types_by_name['MovieID']
_MOVIETITLE = DESCRIPTOR.message_types_by_name['MovieTitle']
_MOVIEUPDATERATING = DESCRIPTOR.message_types_by_name['MovieUpdateRating']
_MOVIEDATA = DESCRIPTOR.message_types_by_name['MovieData']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
MovieID = _reflection.GeneratedProtocolMessageType('MovieID', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEID,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:MovieID)
  })
_sym_db.RegisterMessage(MovieID)

MovieTitle = _reflection.GeneratedProtocolMessageType('MovieTitle', (_message.Message,), {
  'DESCRIPTOR' : _MOVIETITLE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:MovieTitle)
  })
_sym_db.RegisterMessage(MovieTitle)

MovieUpdateRating = _reflection.GeneratedProtocolMessageType('MovieUpdateRating', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEUPDATERATING,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:MovieUpdateRating)
  })
_sym_db.RegisterMessage(MovieUpdateRating)

MovieData = _reflection.GeneratedProtocolMessageType('MovieData', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEDATA,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:MovieData)
  })
_sym_db.RegisterMessage(MovieData)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_MOVIE = DESCRIPTOR.services_by_name['Movie']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIEID._serialized_start=15
  _MOVIEID._serialized_end=36
  _MOVIETITLE._serialized_start=38
  _MOVIETITLE._serialized_end=65
  _MOVIEUPDATERATING._serialized_start=67
  _MOVIEUPDATERATING._serialized_end=114
  _MOVIEDATA._serialized_start=116
  _MOVIEDATA._serialized_end=188
  _EMPTY._serialized_start=190
  _EMPTY._serialized_end=197
  _MOVIE._serialized_start=200
  _MOVIE._serialized_end=464
# @@protoc_insertion_point(module_scope)
